import { PageHeader, SectionIntro } from "@/components/design";

const programs = [["B.Tech","Computer Science & Engineering","120 Seats","Algorithms, software engineering, computer networks, databases, and systems."],["B.Tech","CSE (AI & Machine Learning)","60 Seats","Artificial intelligence, machine learning, deep learning, and intelligent systems."],["BCA","Bachelor of Computer Application","60 Seats","Programming, web technologies, databases, cloud computing, and application development."],["BBA","Bachelor of Business Administration","60 Seats","Management, accounting, entrepreneurship, analytics, and organisational leadership."]];
const departments = [["Computing","Computer Science & Engineering","Core engineering and emerging computing programs supported by modern labs and industry-aligned learning."],["Applied Sciences","Science & Humanities","Foundation courses in mathematics, physics, communication, professional ethics, and the humanities."],["Management","Business Administration","Practical business education focused on leadership, enterprise, analytics, and decision-making."],["Computer Applications","BCA Department","Application-oriented computing education with a strong foundation in programming and modern platforms."]];

export default function AcademicsPage() { return <main>
  <PageHeader label="Academics" title="Programs & Departments">Career-focused programs combining strong fundamentals, practical learning, and modern technology.</PageHeader>
  <section className="section"><div className="container"><SectionIntro label="Programs" title="Degree Programs Offered">Four undergraduate pathways designed for technology and management careers.</SectionIntro><div className="courses-grid">{programs.map(([type,name,seats,detail])=><article className="course-card" key={name}><div className="dept">{type}</div><h3>{name}</h3><p>{detail}</p><span className="seats">{seats} · Full Time · KTU</span></article>)}</div></div></section>
  <section className="section surface"><div className="container"><SectionIntro label="Departments" title="Academic Departments">Interdisciplinary learning supported by experienced faculty and specialised facilities.</SectionIntro><div className="two-grid">{departments.map(([tag,name,detail])=><article className="dept-card" key={name}><p className="section-label">{tag}</p><h3>{name}</h3><p>{detail}</p></article>)}</div></div></section>
  <section className="section"><div className="container"><SectionIntro label="Learning at CEK" title="Academic Framework">A balanced approach that connects classroom knowledge with practical application.</SectionIntro><div className="why-grid">{[["01","KTU Curriculum","Outcome-based curriculum with continuous assessment, laboratories, projects, and university examinations."],["02","Hands-on Learning","Laboratory sessions, mini projects, industrial visits, technical workshops, and final-year capstones."],["03","Digital Resources","IEEE and IET journals, NPTEL courses, NKN connectivity, smart classrooms, and a central library."],["04","Expert Sessions","Invited talks, workshops, professional chapters, and sessions by experts from industry and premier institutes."],["05","Innovation","IEDC, technical forums, hackathons, project showcases, and Kerala Startup Mission opportunities."],["06","Career Readiness","Aptitude training, communication development, mock interviews, and placement preparation."]].map(([n,t,d])=><article className="why-item" key={n}><div className="num">{n}</div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
</main>; }
