import Link from "next/link";
import { PageHeader, Placeholder, SectionIntro } from "@/components/design";

export default function AdmissionsPage() { return <main>
  <PageHeader label="Admissions" title="Admission 2026">Begin your journey at CEK. Applications are open for B.Tech, BCA, and BBA programs for the 2026–27 academic year.</PageHeader>
  <section style={{padding:0,borderBottom:"1px solid var(--border)"}}><div className="container"><Placeholder icon="🎓" title="Admissions at CEK" hint="Add a photo of new students, orientation, or the campus" className="wide-placeholder"/></div></section>
  <section className="section"><div className="container"><SectionIntro label="Application Process" title="How to Apply">Choose your program and follow the appropriate admission pathway.</SectionIntro><div className="step-grid">{[["01","Check Eligibility","Review the eligibility requirements for your chosen B.Tech, BCA, or BBA program."],["02","Apply Through the Portal","B.Tech merit admission is through CEE Kerala. Management and NRI applicants follow IHRD notifications."],["03","Document Verification","Report with original documents, certificates, photographs, and the prescribed admission fee."]].map(([n,t,d])=><article className="step-card" key={n}><div className="num">{n}</div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="section surface"><div className="container"><SectionIntro label="Fees" title="Fee Structure & Waivers">Transparent, government-regulated fees with support for eligible students.</SectionIntro><div className="two-grid"><article className="info-card"><h3>B.Tech Programs</h3><p><strong>Merit quota:</strong> As prescribed by the Government of Kerala and CEE.</p><p><strong>Management/NRI quota:</strong> As notified by IHRD for the academic year.</p><p>Examination, university, PTA, and refundable caution deposit charges may apply separately.</p></article><article className="info-card"><h3>Scholarships & Concessions</h3><ul><li>Government e-Grantz support for eligible students</li><li>Merit-cum-means scholarships</li><li>SC/ST/OEC fee concessions as per rules</li><li>Alumni-supported assistance for deserving students</li></ul></article></div></div></section>
  <section className="section"><div className="container"><SectionIntro label="Seats" title="Program Intake & Quotas"/><div className="courses-grid">{[["B.Tech","Computer Science & Engineering","120 Seats · Merit / Management / NRI"],["B.Tech","CSE (AI & Machine Learning)","60 Seats · Merit / Management / NRI"],["BCA","Bachelor of Computer Application","60 Seats · As per KTU/IHRD norms"],["BBA","Bachelor of Business Administration","60 Seats · As per KTU/IHRD norms"]].map(([d,t,s])=><article className="course-card" key={t}><div className="dept">{d}</div><h3>{t}</h3><span className="seats">{s}</span></article>)}</div></div></section>
  <section className="section surface"><div className="container"><SectionIntro label="Timeline" title="Fee & Important Dates"/><div className="two-grid"><article className="info-card"><h3>Admission 2026</h3><ul><li>Applications open — June 2026</li><li>Document verification — As per allotment memo</li><li>Orientation — Before commencement of classes</li></ul></article><article className="info-card"><h3>Odd Semester Fee</h3><ul><li>Fee remittance opens — 15 June 2026</li><li>Without fine — Until 7 July 2026</li><li>Always verify dates against the latest official notice</li></ul></article></div></div></section>
  <section className="section"><div className="container"><SectionIntro label="Downloads" title="Important Documents"/><div className="doc-grid">{[["📄","AICTE EoA 2026–27","Approval document"],["📋","KTU Affiliation","Extension of affiliation"],["📑","Mandatory Disclosure","Institutional disclosure"],["💳","Fee Notice 2026–27","Remittance schedule"]].map(([i,n,h])=><a className="doc-link" href="#" key={n}><span className="icon">{i}</span><span><span className="name">{n}</span><br/><span className="hint">{h}</span></span></a>)}</div></div></section>
  <section className="section"><div className="container"><div className="cta-banner"><h2>Ready to Join CEK?</h2><p>For admission assistance, contact the college office or send us your query.</p><Link className="btn btn-primary" href="/contact">Contact Admissions →</Link></div></div></section>
</main>; }
