import { PageHeader, Placeholder, SectionIntro } from "@/components/design";

const facilities = [["💻","Computer Centre","114+ modern computer systems with high-speed network access and software development facilities."],["📚","Central Library","5,990 volumes, reference texts, IEEE/IET journals, and NPTEL video courses."],["📡","Smart Classrooms","EDUSAT satellite-based interactive learning, projectors, and audiovisual teaching aids."],["🏠","Hostels","Separate boys’ and girls’ hostels with reading rooms, recreation, and medical support."],["🏋️","Sports & Gym","Indoor and outdoor sports facilities, a gymnasium, and inter-collegiate competition support."],["☕","Campus Amenities","Cafeteria, cooperative society, language development centre, and counselling services."]];

export default function AboutPage() {
  return <main>
    <PageHeader label="About CEK" title="About College of Engineering Kottarakkara">A premier government-managed technical institution in Kollam, Kerala — committed to excellence in engineering education since 2004.</PageHeader>
    <section style={{padding:0,borderBottom:"1px solid var(--border)"}}><div className="container"><Placeholder icon="🏛️" title="College Campus — Aerial or Front View" hint="Add a wide campus photo showing the main building or entrance" className="wide-placeholder"/></div></section>
    <section className="section"><div className="container content-grid"><div className="body-copy"><p>College of Engineering Kottarakkara (CEK) is a distinguished technical institution established in 2004 under the Institute of Human Resources Development (IHRD). It is approved by AICTE and affiliated with APJ Abdul Kalam Technological University (KTU).</p><p>Located in Kottarakkara, Kollam, CEK enjoys excellent connectivity. The campus is part of the National Knowledge Network and features a digitally enabled learning environment with smart classrooms and ICT facilities.</p><p>Beyond academics, CEK promotes a vibrant culture through student clubs, technical forums, innovation cells, and professional chapters such as IEEE, ISTE, and CSI.</p><p>Students are encouraged to explore project-based learning, community service, entrepreneurship, and research alongside faculty.</p></div><div><div className="card" style={{marginBottom:20}}><h3>College Details</h3><ul><li>Established: 2004</li><li>Type: Government (Managed by IHRD)</li><li>Affiliated to: APJ Abdul Kalam Technological University</li><li>Approved by: AICTE</li><li>Office Hours: 9:30 am – 4:30 pm</li><li>Principal: Dr. Manoj Ray D</li></ul></div><div className="card"><h3>Timeline</h3>{[["2004","College established under IHRD, Government of Kerala."],["2015","Affiliated to APJ Abdul Kalam Technological University."],["2024","New programs in AI & ML, BCA, and BBA introduced."],["2026","AICTE approval extended and admissions opened."]].map(([y,d])=><div className="timeline-item" key={y}><div className="year">{y}</div><div className="desc">{d}</div></div>)}</div></div></div></section>
    <section className="section surface"><div className="container vm-grid"><article className="vm-card"><div className="icon">🔭</div><h3>Our Vision</h3><p>To emerge as a centre of excellence in engineering education and research, fostering innovation, ethical values, and technological competence.</p></article><article className="vm-card"><div className="icon">⚙️</div><h3>Our Mission</h3><p>To provide high-quality technical education that nurtures creativity, critical thinking, professional ethics, and service to society.</p></article></div></section>
    <section className="section"><div className="container"><SectionIntro label="Leadership" title="Key Administration"/><div className="two-grid"><article className="club-card"><h3>Dr. Manoj Ray D</h3><p>Principal — leading CEK’s academic mission, institutional development, and student-centred initiatives.</p></article><article className="club-card"><h3>IHRD, Government of Kerala</h3><p>CEK is managed by the Institute of Human Resources Development, an autonomous educational institution established by the Government of Kerala.</p></article></div></div></section>
    <section className="section surface"><div className="container"><SectionIntro label="Infrastructure" title="Campus Facilities">A connected campus designed for focused learning, experimentation, and student wellbeing.</SectionIntro><div className="why-grid">{facilities.map(([i,t,d])=><article className="why-item" key={t}><div style={{fontSize:24,marginBottom:8}}>{i}</div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  </main>;
}
