"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Placeholder, SectionIntro } from "@/components/design";

const jobs = [
  { company:"Tata Consultancy Services", abbrev:"TCS", role:"Systems Engineer", location:"Thiruvananthapuram", salary:"₹7L–9L", dept:"cse", deadline:"15 Jul 2026", color:"#0079c1", desc:"Enterprise systems, cloud platforms, and digital transformation projects for global clients." },
  { company:"Infosys", abbrev:"INF", role:"Digital Specialist Engineer", location:"Mysuru / Bengaluru", salary:"₹8L–12L", dept:"cse", deadline:"20 Jul 2026", color:"#007cc3", desc:"Next-generation AI/ML, cloud-native applications, and automation frameworks." },
  { company:"Wipro", abbrev:"W", role:"Project Engineer", location:"Kochi", salary:"₹5.5L–7.5L", dept:"cse", deadline:"10 Jul 2026", color:"#8e24aa", desc:"Full-stack development, testing, and client delivery across multiple domains." },
  { company:"Tata Elxsi", abbrev:"TE", role:"Graduate Engineer Trainee", location:"Thiruvananthapuram", salary:"₹6L–8L", dept:"core", deadline:"25 Jul 2026", color:"#283593", desc:"Embedded systems, automotive software, broadcast, and IoT solutions." },
  { company:"Amazon Development Centre", abbrev:"AZ", role:"Software Development Engineer", location:"Bengaluru / Hyderabad", salary:"₹12L–18L", dept:"cse", deadline:"20 Aug 2026", color:"#d47c00", desc:"Distributed systems, high-scale services, and complex engineering problems." },
  { company:"Quantiphi Analytics", abbrev:"QA", role:"Data Engineer", location:"Bengaluru / Mumbai", salary:"₹7L–10L", dept:"aiml", deadline:"12 Aug 2026", color:"#0062ff", desc:"High-impact machine learning and data engineering solutions." },
  { company:"Federal Bank", abbrev:"FB", role:"Management Trainee", location:"Kerala", salary:"₹6L–8L", dept:"bba", deadline:"08 Jul 2026", color:"#b71c1c", desc:"Branch management, credit analysis, and banking operations." },
  { company:"Zoho Corporation", abbrev:"ZO", role:"Software Developer", location:"Chennai", salary:"₹6L–10L", dept:"bca", deadline:"10 Aug 2026", color:"#e65100", desc:"Build SaaS products used by millions with strong programming fundamentals." }
];

export default function PlacementsPage() {
  const [query,setQuery] = useState("");
  const [dept,setDept] = useState("all");
  const [selected,setSelected] = useState<(typeof jobs)[number] | null>(null);
  const filtered = useMemo(() => jobs.filter(j => (dept === "all" || j.dept === dept || dept === "core" && j.dept === "core") && `${j.company} ${j.role} ${j.location}`.toLowerCase().includes(query.toLowerCase())),[query,dept]);
  return <main>
    <div className="placement-page-head"><div className="container"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span><span>Placements</span></div><h1>Training & Placements</h1></div></div>
    <section className="placement-hero"><div className="container"><h1>Building Careers at <span className="highlight">CEK</span></h1><p>Our Training & Placement Cell works year-round to prepare students for rewarding careers. From aptitude training and mock interviews to industry partnerships — we ensure every student is placement-ready.</p><div className="tpc-img-row"><Placeholder icon="🏢" title="Campus Drive" hint="Add photo from a placement drive or company visit"/><Placeholder icon="🎯" title="Training Session" hint="Add photo from aptitude training or workshop"/></div><div className="placement-stats">{[["92%","Placement Rate 2025"],["45+","Recruiting Partners"],["₹8.5L","Highest Package 2025"],["₹4.2L","Average Package 2025"]].map(([n,l])=><div className="placement-stat" key={l}><div className="num">{n}</div><div className="label">{l}</div></div>)}</div></div></section>
    <section className="section"><div className="container"><div className="filters-bar"><div className="search-wrap"><span className="icon">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search companies, roles, locations..." aria-label="Search opportunities"/></div><div className="filter-group">{[["all","All"],["cse","CSE"],["aiml","AI & ML"],["bca","BCA"],["bba","BBA"],["core","Core / All"]].map(([v,l])=><button type="button" className={`filter-chip ${dept===v?"active":""}`} onClick={()=>setDept(v)} key={v}>{l}</button>)}</div></div><p className="results-meta">Showing <strong>{filtered.length}</strong> opportunities</p><div className="jobs-grid">{filtered.map(job=><article className="job-card" key={`${job.company}-${job.role}`}><div className="job-card-header"><div className="logo-placeholder" style={{background:job.color}}>{job.abbrev}</div><div className="job-info"><h3>{job.role}</h3><div className="company">{job.company}</div></div><div className="deadline"><div className="dt-label">Apply by</div><div className="dt-value">{job.deadline}</div></div></div><div className="job-tags"><span>{job.role}</span><span>{job.location}</span></div><p>{job.desc}</p><div className="job-card-footer"><div className="salary">{job.salary} <span>p.a.</span></div><button className="btn btn-primary btn-sm" type="button" onClick={()=>setSelected(job)}>View & Apply</button></div></article>)}</div>{!filtered.length && <div className="empty-state"><div>⌕</div><h3>No matching opportunities</h3><p>Try adjusting your filters or search terms.</p></div>}</div></section>
    <section className="section surface"><div className="container"><SectionIntro label="How We Prepare" title="Placement Process">From day one, our holistic framework prepares every student for the professional world.</SectionIntro><div className="activities-grid">{[["01","Aptitude Training","Quantitative, logical reasoning, and verbal ability sessions."],["02","Technical Workshops","Domain training, coding bootcamps, and hands-on labs."],["03","Mock Interviews","One-on-one interviews with industry professionals and faculty."],["04","Industry Connect","Campus drives, company visits, guest lectures, and alumni networking."]].map(([n,t,d])=><article className="activity-card" key={n}><div className="icon" style={{color:"var(--accent)",fontWeight:700}}>{n}</div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
    <section className="section" style={{background:"var(--accent-glow)",textAlign:"center"}}><div className="container"><SectionIntro label="Training & Placement Cell" title="Have Questions?"/><p className="section-sub" style={{margin:"0 auto 28px"}}>Contact the TPC office for campus drive schedules, pre-placement training, or career guidance.</p><Link className="btn btn-primary" href="/contact">Get in Touch →</Link></div></section>
    {selected && <div className="modal-overlay open" role="dialog" aria-modal="true" aria-label={`Apply for ${selected.role}`} onMouseDown={()=>setSelected(null)}><div className="job-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close">×</button><h2>{selected.role}</h2><p className="modal-company">{selected.company}</p><div className="modal-details"><div><small>Location</small><strong>{selected.location}</strong></div><div><small>Salary</small><strong>{selected.salary}</strong></div><div><small>Department</small><strong>{selected.dept.toUpperCase()}</strong></div><div><small>Deadline</small><strong>{selected.deadline}</strong></div></div><p className="modal-description">{selected.desc}</p><form onSubmit={e=>{e.preventDefault();setSelected(null);}}><h3>Apply for this position</h3><div className="form-group"><label>Full Name</label><input required placeholder="Your full name"/></div><div className="form-group"><label>Email</label><input required type="email" placeholder="you@cekottarakkara.ac.in"/></div><button className="btn btn-primary" type="submit">Submit Application</button></form></div></div>}
  </main>;
}
