import { PageHeader, Placeholder, SectionIntro } from "@/components/design";

const clubs = [["📡","IEEE Student Branch","Technical talks, workshops, exhibitions, outreach, global resources, networking, and professional development."],["💡","IEDC — Innovation Cell","Creativity, leadership, entrepreneurship, cluster hackathons, and opportunities supported by Kerala Startup Mission."],["🤖","REACT — Technical Forum","Robotics, automation, coding challenges, hackathons, project showcases, and peer learning."],["🌿","NSS — National Service Scheme","Community service, environmental awareness, health drives, social outreach, and student leadership."],["🎨","Arts & Sports Clubs","Annual arts festivals, sports meets, tournaments, debates, literary events, and cultural activities."],["📰","College Magazine & Newsletter","Student achievements, research, creative writing, campus updates, editing, writing, and design."]];
const services = [["🎯 Training & Placement Cell","Aptitude, group discussions, mock interviews, behavioural sessions, and career counselling."],["🧠 Professional Counselling","Stress management, emotional intelligence, personal growth, and confidential student support."],["📚 Digital Library","IEEE and IET journals, NPTEL courses, reference texts, and 5,990 book volumes."],["🏠 Hostel & Amenities","Separate hostels, cafeteria, recreation, medical support, sports facilities, and gymnasium."]];

export default function StudentLifePage() { return <main>
  <PageHeader label="Student Life" title="Life at CEK">Beyond the classroom — a vibrant campus community built on innovation, leadership, and service.</PageHeader>
  <section className="section"><div className="container"><SectionIntro label="Clubs & Forums" title="Student Organisations">Diverse platforms for students to explore, create, serve, and lead.</SectionIntro><div className="club-grid">{clubs.map(([i,t,d])=><article className="club-card club-layout" key={t}><Placeholder icon={i} title={`${t} Event`} className="club-thumb"/><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
  <section className="section surface"><div className="container"><SectionIntro label="Achievements" title="Recent Highlights">CEK students excel in technical competitions, volunteering, sports, and community leadership.</SectionIntro><div className="achievement-grid">{[["🏆","1st Prize — IEDC Hackathon","First prize at the IEDC Kollam Cluster Level Hackathon."],["⭐","IEEE Outstanding Volunteer","Special mention from IEEE Kerala Section for exceptional service."],["♟️","Runner-Up — KTU Chess","Runner-up in the KTU B Zone Chess Competition."]].map(([i,t,d])=><article className="achievement-card" key={t}><Placeholder icon={i} title="Achievement Photo"/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="section"><div className="container"><SectionIntro label="Support" title="Student Services">Support that helps every student thrive academically, professionally, and personally.</SectionIntro><div className="services-grid">{services.map(([t,d])=><article className="club-card" key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="section surface"><div className="container"><SectionIntro label="Events" title="Upcoming & Recent Events">Stay connected with the latest happenings at CEK.</SectionIntro>{[["🎓","01","Jul","Commencement of Classes","Odd semester classes for 2026–27 begin. Welcome to all returning and new students."],["📋","15","Jun","Fee Remittance Opens","Fee remittance for B.Tech and BCA odd semesters begins."],["🎪","27","Feb","NCMASE2026 — National Conference","National Conference on multidisciplinary approaches in AI and sustainable engineering."]].map(([i,d,m,t,p])=><article className="event-with-img" key={t}><Placeholder icon={i} title={t} className="event-thumb"/><div><div className="event-date"><div><div className="event-day">{d}</div><div className="event-month">{m}</div></div><h3>{t}</h3></div><p>{p}</p></div></article>)}</div></section>
</main>; }
